### ISSUE TITLE
indent guide problems

### ISSUE THREAD

**Issue by zouqilin** [tlhunter/vimrc#12]
could you add indent guide into your vim
https://github.com/nathanaelkane/vim-indent-guides

**Comment by tlhunter** [comment]
Seems a bit too distracting for my taste... Also, it highlights NERDTree as well:

![screen shot 2015-06-02 at 23 15 06](https://cloud.githubusercontent.com/assets/551402/7953753/4507d0f2-097d-11e5-8b27-c973818f83aa.png)

**Comment by zouqilin** [comment]
why didn't show indent-guide in my vim???

**Comment by tlhunter** [comment]
Once you install it locally you need to activate it with `<Leader>ig`.

**Comment by zouqilin** [comment]
ok, thk.
