### ISSUE TITLE
YouCompleteMe

### ISSUE THREAD

**Issue by phackwer** [tlhunter/vimrc#13]
How about adding auto complete with this plugin?

**Comment by phackwer** [comment]
https://valloric.github.io/YouCompleteMe/

**Comment by tlhunter** [comment]
I used to use an auto complete, but the thing drove me nuts and I eventually removed it:

https://github.com/tlhunter/vimrc/commit/acae43634d7e0607aab5286dfc12c825998758f3

The biggest annoyance is that it would be enabled when editing text documents, and pressing enter would replace words in sentences. I'll give YCM a try, maybe it's less annoying.

**Comment by juizmill** [comment]
auto-complete would be nice :)

**Comment by stonemaster** [comment]
Just as a side note: if you are on Debian/Ubuntu you can install YouCompleteMe directly from the repositories. It works like charm together with tlhunter/vimrc.

**Comment by tlhunter** [comment]
YCM takes a few too many steps to get working. I'm afraid it would make this vimrc less attractive to new VIM users.

That said, installing YCM works the same way whether you're using this vimrc or your own, so anyone wanting to use YCM (or any other module) should install it themselves.
