### ISSUE TITLE
Ack may not work for old ack.vim

### ISSUE THREAD

**Issue by reverland** [tlhunter/vimrc#16]
Cool vim configurations! Really enjoy it.

However, I find that the ack.vim not work for me.

After some test I update it to the git version and it works now.

Just as a reminder for others who has met the same problem.

My machine is Ubuntu Linux 14.04 LTS and the vim is installed from the main repository

**Comment by tlhunter** [comment]
Fixed in e71c7f8e70ffe80488daa477739d778686c61017
