### ISSUE TITLE
Color Scheme Removed Problem.

### ISSUE THREAD

**Issue by gaofeibupt** [tlhunter/vimrc#21]
Hi: 
   I used this vimrc for a long time. Did you had remove some color schemes from master? I cloned this repo from my new pc, but I could not find some color scheme I used in the past. Thanks!

**Comment by tlhunter** [comment]
Yes, many color schemes were removed. You can checkout 5fd11d11e7107ceeb1b337d5e5f4dca78063d2bc to get them back.
